=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/XfireSkin.dtd
<!ELEMENT XfireSkin (SkinDescription,GlobalPrefs?,Strings+,Themes?,Components,MainSkin,ChatSkin,GroupChatSkin,InGameMainSkin,InGameAlertSkin,Popups?)>
 
     <!-- SkinsDescription definition -->
     <!ELEMENT SkinDescription (Author*,Website?,Name,LongName,Version,CompatibleVersion,License?)>
     <!ELEMENT Author (#PCDATA)>
        <!ATTLIST Author Type (original|contributor) "original">
     <!ELEMENT Website (#PCDATA)>
     <!ELEMENT Name (#PCDATA)>
     <!ELEMENT LongName (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT CompatibleVersion (#PCDATA)>
     <!ELEMENT License (#PCDATA)>
 
     <!-- GlobalPrefs definition -->
     <!ELEMENT GlobalPrefs (TooltipColor?,TooltipTextColor?,OnlineSound?,OfflineSound?)>
     <!ELEMENT TooltipColor (#PCDATA)>
     <!ELEMENT TooltipTextColor (#PCDATA)>
     <!ELEMENT OnlineSound (#PCDATA)>
     <!ELEMENT OfflineSound (#PCDATA)>
 
     <!-- Strings definition -->
     <!ELEMENT Strings (String*)>
        <!ATTLIST Strings Lang CDATA "default">
     <!ELEMENT String (#PCDATA)>
        <!ATTLIST String Name CDATA #REQUIRED>
        <!ATTLIST String ResourceId CDATA #IMPLIED>
 
     <!-- Themes definition -->
     <!ELEMENT Themes (Theme*)>
     <!ELEMENT Theme (Colors?,ColorShifts?,Sounds?,Bitmaps?)>
 
     <!ELEMENT Colors (Color*)>
     <!ELEMENT Color (#PCDATA)>
        <!ATTLIST Color Red CDATA #IMPLIED>
        <!ATTLIST Color Green CDATA #IMPLIED>
        <!ATTLIST Color Blue CDATA #IMPLIED>
        <!ATTLIST Color Alpha CDATA #IMPLIED>
 
     <!ELEMENT ColorShifts (ColorShift*)>
     <!ELEMENT ColorShift (#PCDATA)>
        <!ATTLIST ColorShift Red CDATA #IMPLIED>
        <!ATTLIST ColorShift Green CDATA #IMPLIED>
        <!ATTLIST ColorShift Blue CDATA #IMPLIED>
        <!ATTLIST ColorShift Alpha CDATA #IMPLIED>
 
     <!ELEMENT Sounds (Sound*)>
     <!ELEMENT Sound (#PCDATA)>
        <!ATTLIST Sound Name CDATA #REQUIRED>
        <!ATTLIST Sound ResourceId CDATA #IMPLIED>
 
     <!ELEMENT Bitmaps (Bitmap*)>
     <!ELEMENT Bitmap (#PCDATA)>
        <!ATTLIST Bitmap Name CDATA #REQUIRED>
        <!ATTLIST Bitmap ResourceId CDATA #IMPLIED>
 
     <!-- Window definitions -->
     <!ELEMENT MainSkin (Tile)>
     <!ELEMENT ChatSkin (Tile)>
     <!ELEMENT GroupChatSkin (Tile)>
     <!ELEMENT InGameAlertSkin (Tile)>
     <!ELEMENT InGameMainSkin (Tile)>
 
     <!-- Tiles definition (Layout) -->
     <!ELEMENT Tile (Tile*)>
        <!ATTLIST Tile Name CDATA #REQUIRED>
        <!ATTLIST Tile AlignX (left|center|right) #IMPLIED>
        <!ATTLIST Tile AlignY (top|center|bottom) #IMPLIED>
        <!ATTLIST Tile Top CDATA #IMPLIED>
        <!ATTLIST Tile Left CDATA #IMPLIED>
        <!ATTLIST Tile Bottom CDATA #IMPLIED>
        <!ATTLIST Tile Right CDATA #IMPLIED>
        <!ATTLIST Tile Width CDATA #IMPLIED>
        <!ATTLIST Tile Height CDATA #IMPLIED>
        <!ATTLIST Tile Component CDATA #REQUIRED>
        <!ATTLIST Tile MinWidth CDATA #IMPLIED>
        <!ATTLIST Tile MinHeight CDATA #IMPLIED>
        <!ATTLIST Tile DefaultWidth CDATA #IMPLIED>
        <!ATTLIST Tile DefaultHeight CDATA #IMPLIED>
        <!ATTLIST Tile ResizeX CDATA #IMPLIED>
        <!ATTLIST Tile ResizeY CDATA #IMPLIED>
        <!ATTLIST Tile X CDATA #IMPLIED>
        <!ATTLIST Tile Y CDATA #IMPLIED>
        <!ATTLIST Tile Z CDATA #IMPLIED>
        <!ATTLIST Tile IndentLeft CDATA #IMPLIED>
        <!ATTLIST Tile IndentRight CDATA #IMPLIED>
        <!ATTLIST Tile IndentTop CDATA #IMPLIED>
        <!ATTLIST Tile IndentBottom CDATA #IMPLIED>
        <!ATTLIST Tile JustX CDATA #IMPLIED>
        <!ATTLIST Tile JustY CDATA #IMPLIED>
        <!ATTLIST Tile BindX CDATA #IMPLIED>
        <!ATTLIST Tile BindY CDATA #IMPLIED>
        <!ATTLIST Tile OutdentLeft CDATA #IMPLIED>
        <!ATTLIST Tile OutdentRight CDATA #IMPLIED>
        <!ATTLIST Tile OutdentTop CDATA #IMPLIED>
        <!ATTLIST Tile OutdentBottom CDATA #IMPLIED>

     <!-- Components definition (Layout) -->
     <!ELEMENT Components (Component*)>
     <!ELEMENT Component (Triggers?,Images*,Text*,Popup?,ProgressBar?)>
        <!ATTLIST Component Name CDATA #REQUIRED>
        <!ATTLIST Component Default CDATA #IMPLIED>
        <!ATTLIST Component Class CDATA #IMPLIED>
        <!ATTLIST Component Stretch CDATA #IMPLIED>
        <!ATTLIST Component Events CDATA #IMPLIED>
        <!ATTLIST Component Tooltip CDATA #IMPLIED>
        <!ATTLIST Component Accelerator CDATA #IMPLIED>
        <!ATTLIST Component Cursor CDATA #IMPLIED>
        <!ATTLIST Component ControlGroupId CDATA #IMPLIED>
        <!ATTLIST Component TooltipColor CDATA #IMPLIED>
        <!ATTLIST Component TooltipTextColor CDATA #IMPLIED>
        <!ATTLIST Component MouseOver CDATA #IMPLIED>
        <!ATTLIST Component DisabledTooltip CDATA #IMPLIED>
        <!ATTLIST Component WindowFocus CDATA #IMPLIED>
        <!ATTLIST Component Color CDATA #IMPLIED>
        <!ATTLIST Component Scrollbar CDATA #IMPLIED>
        <!ATTLIST Component PushType CDATA #IMPLIED>
        <!ATTLIST Component GroupId CDATA #IMPLIED>
        <!ATTLIST Component CaretColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionSelectorColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColorInActive CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColorInActive CDATA #IMPLIED>
 
    <!ELEMENT Triggers (Trigger*)>
    <!ELEMENT Trigger (#PCDATA)>
        <!ATTLIST Trigger Type (OnInit|OnAppStartRefreshServers|OnAppStopRefreshServers|OnDownloadComplete|OnActivate|OnDeactivate|OnLeftClick|OnRightClick|OnLeftButtonDown|OnRightButtonDown|OnLeftDoubleClick|OnRightDoubleClick|OnXfireUrlDownload) #IMPLIED>
  
    <!ELEMENT Images (Image*)>
        <!ATTLIST Images State (normal|hover|disabled|overlay) #IMPLIED>
        <!ATTLIST Images Color CDATA #IMPLIED>
        <!ATTLIST Images HeaderColor CDATA #IMPLIED>
        <!ATTLIST Images ColorShift CDATA #IMPLIED>
    
    <!ELEMENT Image (#PCDATA)>
        <!ATTLIST Image Type (topleft|top|topright|left|middle|right|bottomleft|bottom|bottomright|headerleft|headermiddle|headerright|headerarrowup|headerarrowdown|headercollapsed|headerexpanded) #IMPLIED>
    
    <!ELEMENT Popup (#PCDATA)>
        <!ATTLIST Popup SaveState CDATA #IMPLIED>

    <!ELEMENT ProgressBar (#PCDATA)>
        <!ATTLIST ProgressBar OutlineColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar BGColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar TextColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar Radius CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillRadius CDATA #IMPLIED>
    
    <!ELEMENT Text (#PCDATA)>
        <!ATTLIST Text Font CDATA #IMPLIED>
        <!ATTLIST Text State CDATA #IMPLIED>
        <!ATTLIST Text Size CDATA #IMPLIED>
        <!ATTLIST Text Bold CDATA #IMPLIED>
        <!ATTLIST Text Italic CDATA #IMPLIED>
        <!ATTLIST Text Background CDATA #IMPLIED>
        <!ATTLIST Text color_friend CDATA #IMPLIED>
        <!ATTLIST Text color_fof CDATA #IMPLIED>
        <!ATTLIST Text color_offline CDATA #IMPLIED>
        <!ATTLIST Text color_selected CDATA #IMPLIED>
        <!ATTLIST Text color_nonfocus CDATA #IMPLIED>
        <!ATTLIST Text color_selectedtext CDATA #IMPLIED>
        <!ATTLIST Text color_header CDATA #IMPLIED>
    
    <!ELEMENT Popups (Tile+)>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Popups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Popups SYSTEM "XfireSkin.dtd">

<Popups>
    <!--
    //////////////////////////////////////////////
    // Main Info View
    //////////////////////////////////////////////
    -->
    <Tile Name="MainInfoViewPopup" X="MainWindow.Right-13" Z="0" ResizeY="100" IndentTop="23" IndentBottom="23" Component="MainInfoViewPopup">
        <!--
        //////////////////////////////////////////////
        // Resize Grippers
        //////////////////////////////////////////////
        -->
        <Tile Name="MainInfoResizeR" X="13" Z="98" JustX="Right" ResizeY="100" Component="PopupResizeGripperR" />



        <!--
        //////////////////////////////////////////////
        // Window Frame
        //////////////////////////////////////////////
        -->
        <!-- <Tile Name="MainInfoViewButtonMask" X="60" Z="50" JustX="Left" ResizeY="100" Component="InfoViewButtonMask" /> -->
        <Tile Name="MainInfoTopRow" Z="1" JustY="Top" ResizeX="100" IndentRight="13" Component="InfoViewTopRow" />
        <Tile Name="MainInfoLeftSide" Z="1" ResizeY="100" IndentTop="MainInfoTopRow.Height" IndentBottom="MainInfoBottomRow.Height" Component="InfoViewLeftSide" />
        <Tile Name="MainInfoBackground" Z="1" ResizeX="100" ResizeY="100" IndentTop="MainInfoTopRow.Height" IndentRight="MainInfoRightSide.Width+13" IndentBottom="MainInfoBottomRow.Height" IndentLeft="MainInfoLeftSide.Width" Component="InfoViewBackground" />
        <Tile Name="MainInfoRightSide" X="13" Z="50" JustX="Right" ResizeY="100" IndentTop="MainInfoTopRow.Height" IndentBottom="MainInfoBottomRow.Height" Component="InfoViewRightSide" />
        <Tile Name="MainInfoBottomRow" Z="1" JustY="Bottom" ResizeX="100" IndentRight="13" Component="InfoViewBottomRow" />



        <!--
        //////////////////////////////////////////////
        // Content
        //////////////////////////////////////////////
        -->
        <Tile Name="MainInfoContentContainer" Z="60" ResizeX="100" ResizeY="100" IndentTop="7" IndentRight="18" IndentBottom="7" Component="ContentContainer">
            <Tile Name="MainInfoContent" Z="99" ResizeX="100" ResizeY="100" Component="MainInfoViewContent" />
        </Tile>
        
        <Tile Name="MainInfoViewButton" Z="99" JustX="Right" JustY="Center" Component="ButtonMainInfoIn" />
    </Tile>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Chat Info View
    //////////////////////////////////////////////
    -->
    <Tile Name="ChatInfoViewPopup" X="ChatWindow.Right-13" Z="0" ResizeY="100" IndentTop="23" IndentBottom="23" Component="ChatInfoViewPopup">
        <!--
        //////////////////////////////////////////////
        // Resize Grippers
        //////////////////////////////////////////////
        -->
        <Tile Name="ChatInfoResizeR" X="13" Z="98" JustX="Right" ResizeY="100" Component="PopupResizeGripperR" />



        <!--
        //////////////////////////////////////////////
        // Window Frame
        //////////////////////////////////////////////
        -->
        <!-- <Tile Name="ChatInfoViewButtonMask" X="83" Z="50" JustX="Left" JustY="Bottom" Component="ChatInfoViewButtonMask" /> -->
        <Tile Name="ChatInfoTopRow" Z="1" JustY="Top" ResizeX="100" IndentRight="13" Component="InfoViewTopRow" />
        <Tile Name="ChatInfoLeftSide" Z="1" ResizeY="100" IndentTop="ChatInfoTopRow.Height" IndentBottom="ChatInfoBottomRow.Height" Component="InfoViewLeftSide" />
        <Tile Name="ChatInfoBackground" Z="1" ResizeX="100" ResizeY="100" IndentTop="ChatInfoTopRow.Height" IndentRight="ChatInfoRightSide.Width+13" IndentBottom="ChatInfoBottomRow.Height" IndentLeft="MainInfoLeftSide.Width" Component="InfoViewBackground" />
        <Tile Name="ChatInfoRightSide" X="13" Z="50" JustX="Right" ResizeY="100" IndentTop="ChatInfoTopRow.Height" IndentBottom="ChatInfoBottomRow.Height" Component="InfoViewRightSide" />
        <Tile Name="ChatInfoBottomRow" Z="1" JustY="Bottom" ResizeX="100" IndentRight="13" Component="InfoViewBottomRow" />



        <!--
        //////////////////////////////////////////////
        // Content
        //////////////////////////////////////////////
        -->
        <Tile Name="ChatInfoContentContainer" Z="60" ResizeX="100" ResizeY="100" IndentTop="7" IndentRight="18" IndentBottom="7" Component="ContentContainer">
            <Tile Name="ChatInfoContent" Z="99" ResizeX="100" ResizeY="100" Component="ChatInfoViewContent" />
        </Tile>
        
        <Tile Name="ChatInfoViewButton" Z="99" JustX="Right" JustY="Center" Component="ButtonChatInfoIn" />
    </Tile>
    
    
    
    <!--
    //////////////////////////////////////////////
    // XIG Tooltip
    //////////////////////////////////////////////
    -->
    <Tile Name="XIGToolTipPopup" JustX="Left" JustY="Top" Component="XIGToolTip" />
    
</Popups>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/Common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <!--
    //////////////////////////////////////////////
    // Opacity Sliders
    //////////////////////////////////////////////
    -->
    <Component Name="XIGOpacitySlider" Class="SliderControl" MinWidth="67" MaxWidth="67" MinHeight="11" MaxHeight="11" ToolTip="XIGAdjustOpacityTip" ToolTipTile="XIGToolTipPopup" Range="255" Step="1" Type="Opacity" DrawOnTopMost="True" />
    
    <Component Name="XIGOpacityTrack" Class="Tile" MinHeight="5" MaxHeight="5" Stretch="ToContent" Type="Track" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="TopLeft">xig_track_left</Image>
            <Image Type="Top">xig_track_middle</Image>
            <Image Type="TopRight">xig_track_right</Image>
        </Images>
    </Component>
    
    <Component Name="XIGOpacityGripper" Class="Tile" MinWidth="6" MaxWidth="6" MinHeight="11" MaxHeight="11" Stretch="ToContent" Type="Gripper" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">xig_track_gripper</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Window Draggers
    //////////////////////////////////////////////
    -->
    <Component Name="XIGWindowDragger" Class="Tile" Default="Activate" DrawOnTopMost="True">
        <Triggers>
            <Trigger Type="OnLeftButtonDown">AppDragWindow</Trigger>
            <Trigger Type="OnDoubleClick">AppMaximize</Trigger>
        </Triggers>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Websearch
    //////////////////////////////////////////////
    -->
    <Component Name="XIGWebSearchEdit" Class="WebSearchEdit" Stretch="ToContent" ToolTip="XIGWebSearchEditTip" ToolTipTile="XIGToolTipPopup" CaretColor="XIGCaretCG" SelectionSelectorColor="BlackCG" SelectionColor="ListColorSelectedCG" SelectionTextColor="ListColorSelectedTextCG" SelectionColor_InActive="ListColorSelectedCG">
        <Triggers>
            <Trigger Type="OnGamePrefBrowserDisabled">State(Disabled)</Trigger>
        </Triggers>
        <Fonts>
            <Font Type="Text" Font="Arial" Size="11" Bold="False" Color="TextFieldTextCG" />
            <Font Type="DisabledText" Font="Arial" Size="11" Bold="False" Italic="True" Color="DisabledTextCG" />
        </Fonts>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // List Items
    //////////////////////////////////////////////
    -->
    <Component Name="XIGListItemBG" Class="Tile" />
    
    <Component Name="XIGListItemBGSelected" Class="Tile" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">xig_list_color_selected_background</Image>
        </Images>
    </Component>
    
    <Component Name="XIGListItemBGAlert" Class="Tile">
        <Images State="Normal">
            <Image Type="Middle">transparent</Image>
        </Images>
        <Images State="Disabled">
            <Image Type="Left">icon_group_chat</Image>
            <Image Type="Middle">icon_group_chat</Image>
            <Image Type="Right">icon_group_chat</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Scrollbars
    //////////////////////////////////////////////
    -->
    <Component Name="XIGVertScrollBar" Class="VertScrollbar" Stretch="ToContent" Scrollbar="XfireScrollbar" />
    
    
    
    <!--
    //////////////////////////////////////////////
    // Buttons
    //////////////////////////////////////////////
    -->
    <!-- <Component Name="XIGButtonClose" Class="PushButton" MinWidth="19" MaxWidth="19" MinHeight="13" MaxHeight="13" Stretch="ToContent" ToolTip="ButtonCloseTip" TooltipTile="XIGToolTipPopup" DrawOnTopmost="True">
        <Triggers>
            <Trigger Type="OnClick">HideWindow</Trigger>
            <Trigger Type="OnActivate">State(Normal)</Trigger>
            <Trigger Type="OnDeactivate">State(Disabled)</Trigger>
        </Triggers>
        <Images State="Normal">
            <Image Type="Middle">button_close_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_close_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_close_down</Image>
        </Images>
        <Images State="Disabled">
            <Image Type="Middle">button_close_disabled</Image>
        </Images>
    </Component> -->
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/ActiveWindows/Xig2Chats.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGChats" Class="MainWindow" MinWidth="393" MinHeight="323" DefaultWidth="393" DefaultHeight="323" DefaultX="10" DefaultY="10">
        <Triggers>
            <Trigger Type="OnShowChats">ShowWindow</Trigger>
        </Triggers>
    </Component>
    
    <Component Name="XIGChatsTitle" Class="Text" Stretch="ToContent" Events="Transparent" DrawOnTopMost="False">
        <Text Align="Left" Font="Arial" Size="11" Bold="True" Color="XIGActiveWindowTitleCG">XIGChatsTitle</Text>
    </Component>
    
    <!-- Chats list -->
    <Component Name="XIGChatsListContainer" Class="Tile" MinWidth="156" MaxWidth="156" Stretch="ToContent" Events="Transparent" />
    
    <!-- This has a button which is in the buttons section -->
    <Component Name="XIGChatsAllChatsText" Class="Text" MinHeight="13" MaxHeight="13" Stretch="ToContent">
        <Text Font="Arial" Size="11" Bold="True" Align="Left" Color="HeaderTextCG">Active Chats</Text>
    </Component>
    
    <Component Name="XIGChatsList" Class="ChatsList" ToolTipTile="XIGToolTipPopup" ItemIndentLeft="5">
        <Fonts>
            <Font Type="DisplayName" Font="Arial" Size="11" Bold="True" Color="ListFriendTextCG" />
            <Font Type="OfflineDisplayName" Font="Arial" Size="11" Bold="False" Italics="False" Color="ListOfflineTextCG" />
            <Font Type="SelectedDisplayName" Font="Arial" Size="11" Bold="True" Italics="False" Color="ListColorSelectedTextCG" />
        </Fonts>
        <Images State="AllChatsIcon">
            <Image Type="Middle">icon_group_chat</Image>
        </Images>
        <Images State="RoomIcon">
            <Image Type="Middle">icon_group_chat</Image>
        </Images>
        <Images State="SingleChatIcon">
            <Image Type="Middle">icon_chat</Image>
        </Images>
        <Images State="Disabled">
            <Image Type="Middle">icon_chat</Image>
        </Images>
    </Component>
    
    <!-- Chats messages -->
    <Component Name="XIGChatsMsgsContainer" Class="Tile" Stretch="ToContent" Events="Transparent" />
    
    <Component Name="XIGChatsMsgsTitleIcon" Class="Tile" Stretch="ToContent" DrawOnTopMost="False">
        <Images State="Normal">
            <Image Type="Middle">%chat_title_icon:15%</Image>
        </Images>
    </Component>
    
    <Component Name="XIGChatsMsgsHeaderText" Class="Text" Stretch="ToContent">
        <Text Font="Arial" Size="12" Bold="False" Color="HeaderTextCG">%chat_title:15%</Text>
    </Component>
    
    <Component Name="XIGChatsChatArea" Class="ChatArea" CaretColor="XIGCaretCG" SelectionSelectorColor="XIGCaretCG" SelectionColor="ListColorSelectedCG" SelectionColor_InActive="ListColorSelectedCG" SelectionTextColor="ListColorSelectedTextCG" SelectionTextColor_InActive="ListColorSelectedTextCG">
        <Fonts>
            <Font Type="RoomLink" Font="Arial" Size="11" Bold="True" Underline="True" Color="ChatOtherHyperLinkCG" />
            <Font Type="Room" Font="Arial" Size="11" Bold="False" Color="ChatOtherTextCG" />
            <!-- Friend sent a link -->
            <Font Type="UserLink" Font="Arial" Size="11" Bold="True" Underline="True" Color="ChatOtherNameCG" />
            <!-- Friends name + text -->
            <Font Type="User" Font="Arial" Size="11" Bold="False" Color="ChatOtherNameCG" />
            <!-- You sent a link -->
            <Font Type="SendLink" Font="Arial" Size="11" Bold="True" Color="ChatPersonalTextCG" />
            <!-- Your name + text -->
            <Font Type="Send" Font="Arial" Size="11" Bold="False" Color="ChatPersonalTextCG" />
        </Fonts>
        <Images State="UserIcon">
            <Image Type="Middle">icon_chat</Image>
        </Images>
        <Images State="UserIconOverlay">
            <Image Type="Middle">icon_chat</Image>
        </Images>
        <Images State="RoomIcon">
            <Image Type="Middle">icon_group_chat</Image>
        </Images>
        <Images State="RoomIconOverlay">
            <Image Type="Middle">icon_group_chat</Image>
        </Images>
    </Component>
    
    <Component Name="XIGChatsChatEdit" Class="ChatEdit" MinHeight="20" MaxHeight="20" Stretch="ToContent" CaretColor="XIGCaretCG" SelectionSelectorColor="XIGCaretCG" SelectionColor="ListColorSelectedCG" SelectionTextColor="ListColorSelectedTextCG" DrawOnTopMost="True">
        <Fonts>
            <Font Type="Text" Font="Arial" Size="12" Bold="False" Align="Left" Color="ChatPersonalTextCG" />
        </Fonts>
    </Component>

    <Component Name="XIGChatsChatEditContainer" Class="Tile" MinHeight="23" MaxHeight="23" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="TopLeft">text_top_left</Image>
            <Image Type="Top">text_top_middle</Image>
            <Image Type="TopRight">text_top_right</Image>
            <Image Type="Left">text_leftside_middle</Image>
            <Image Type="Middle">text_middle</Image>
            <Image Type="Right">text_rightside_middle</Image>
            <Image Type="BottomLeft">text_bottom_left</Image>
            <Image Type="Bottom">text_bottom_middle</Image>
            <Image Type="BottomRight">text_bottom_right</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Buttons
    //////////////////////////////////////////////
    -->
    <Component Name="XIGChatsButtonBar" Class="Tile" MinHeight="84" MaxHeight="84" Stretch="ToContent" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">button_bar_left_large</Image>
            <Image Type="Top">button_bar_middle_large</Image>
            <Image Type="TopRight">button_bar_right_large</Image>
        </Images>
    </Component>
    
    <Component Name="XIGActiveWindowButtonAllChats" Class="AllChatsControl" Stretch="ToContent" PushType="Sticky" DrawOnTopMost="False" />
    
    <Component Name="XIGChatsCloseConvo" Class="PushButton" MinWidth="8" MaxWidth="8" MinHeight="8" MaxHeight="8" Stretch="ToContent" ToolTip="ButtonCloseChatTip" ToolTipTile="XIGToolTipPopup" DrawOnTopMost="False">
        <Triggers>
            <Trigger Type="OnClick">AttachedClose</Trigger>
        </Triggers>
        <Images State="Normal">
            <Image Type="Middle">button_xig_active_window_close_chat_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_xig_active_window_close_chat_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_xig_active_window_close_chat_down</Image>
        </Images>
    </Component>
    
    
</Components>
