=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/XfireSkin.dtd
<!ELEMENT XfireSkin (SkinDescription,GlobalPrefs?,Strings+,Themes?,Components,MainSkin,ChatSkin,GroupChatSkin,InGameMainSkin,InGameAlertSkin,Popups?)>
 
     <!-- SkinsDescription definition -->
     <!ELEMENT SkinDescription (Author*,Website?,Name,LongName,Version,CompatibleVersion,License?)>
     <!ELEMENT Author (#PCDATA)>
        <!ATTLIST Author Type (original|contributor) "original">
     <!ELEMENT Website (#PCDATA)>
     <!ELEMENT Name (#PCDATA)>
     <!ELEMENT LongName (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT CompatibleVersion (#PCDATA)>
     <!ELEMENT License (#PCDATA)>
 
     <!-- GlobalPrefs definition -->
     <!ELEMENT GlobalPrefs (TooltipColor?,TooltipTextColor?,OnlineSound?,OfflineSound?)>
     <!ELEMENT TooltipColor (#PCDATA)>
     <!ELEMENT TooltipTextColor (#PCDATA)>
     <!ELEMENT OnlineSound (#PCDATA)>
     <!ELEMENT OfflineSound (#PCDATA)>
 
     <!-- Strings definition -->
     <!ELEMENT Strings (String*)>
        <!ATTLIST Strings Lang CDATA "default">
     <!ELEMENT String (#PCDATA)>
        <!ATTLIST String Name CDATA #REQUIRED>
        <!ATTLIST String ResourceId CDATA #IMPLIED>
 
     <!-- Themes definition -->
     <!ELEMENT Themes (Theme*)>
     <!ELEMENT Theme (Colors?,ColorShifts?,Sounds?,Bitmaps?)>
 
     <!ELEMENT Colors (Color*)>
     <!ELEMENT Color (#PCDATA)>
        <!ATTLIST Color Red CDATA #IMPLIED>
        <!ATTLIST Color Green CDATA #IMPLIED>
        <!ATTLIST Color Blue CDATA #IMPLIED>
        <!ATTLIST Color Alpha CDATA #IMPLIED>
 
     <!ELEMENT ColorShifts (ColorShift*)>
     <!ELEMENT ColorShift (#PCDATA)>
        <!ATTLIST ColorShift Red CDATA #IMPLIED>
        <!ATTLIST ColorShift Green CDATA #IMPLIED>
        <!ATTLIST ColorShift Blue CDATA #IMPLIED>
        <!ATTLIST ColorShift Alpha CDATA #IMPLIED>
 
     <!ELEMENT Sounds (Sound*)>
     <!ELEMENT Sound (#PCDATA)>
        <!ATTLIST Sound Name CDATA #REQUIRED>
        <!ATTLIST Sound ResourceId CDATA #IMPLIED>
 
     <!ELEMENT Bitmaps (Bitmap*)>
     <!ELEMENT Bitmap (#PCDATA)>
        <!ATTLIST Bitmap Name CDATA #REQUIRED>
        <!ATTLIST Bitmap ResourceId CDATA #IMPLIED>
 
     <!-- Window definitions -->
     <!ELEMENT MainSkin (Tile)>
     <!ELEMENT ChatSkin (Tile)>
     <!ELEMENT GroupChatSkin (Tile)>
     <!ELEMENT InGameAlertSkin (Tile)>
     <!ELEMENT InGameMainSkin (Tile)>
 
     <!-- Tiles definition (Layout) -->
     <!ELEMENT Tile (Tile*)>
        <!ATTLIST Tile Name CDATA #REQUIRED>
        <!ATTLIST Tile AlignX (left|center|right) #IMPLIED>
        <!ATTLIST Tile AlignY (top|center|bottom) #IMPLIED>
        <!ATTLIST Tile Top CDATA #IMPLIED>
        <!ATTLIST Tile Left CDATA #IMPLIED>
        <!ATTLIST Tile Bottom CDATA #IMPLIED>
        <!ATTLIST Tile Right CDATA #IMPLIED>
        <!ATTLIST Tile Width CDATA #IMPLIED>
        <!ATTLIST Tile Height CDATA #IMPLIED>
        <!ATTLIST Tile Component CDATA #REQUIRED>
        <!ATTLIST Tile MinWidth CDATA #IMPLIED>
        <!ATTLIST Tile MinHeight CDATA #IMPLIED>
        <!ATTLIST Tile DefaultWidth CDATA #IMPLIED>
        <!ATTLIST Tile DefaultHeight CDATA #IMPLIED>
        <!ATTLIST Tile ResizeX CDATA #IMPLIED>
        <!ATTLIST Tile ResizeY CDATA #IMPLIED>
        <!ATTLIST Tile X CDATA #IMPLIED>
        <!ATTLIST Tile Y CDATA #IMPLIED>
        <!ATTLIST Tile Z CDATA #IMPLIED>
        <!ATTLIST Tile IndentLeft CDATA #IMPLIED>
        <!ATTLIST Tile IndentRight CDATA #IMPLIED>
        <!ATTLIST Tile IndentTop CDATA #IMPLIED>
        <!ATTLIST Tile IndentBottom CDATA #IMPLIED>
        <!ATTLIST Tile JustX CDATA #IMPLIED>
        <!ATTLIST Tile JustY CDATA #IMPLIED>
        <!ATTLIST Tile BindX CDATA #IMPLIED>
        <!ATTLIST Tile BindY CDATA #IMPLIED>
        <!ATTLIST Tile OutdentLeft CDATA #IMPLIED>
        <!ATTLIST Tile OutdentRight CDATA #IMPLIED>
        <!ATTLIST Tile OutdentTop CDATA #IMPLIED>
        <!ATTLIST Tile OutdentBottom CDATA #IMPLIED>

     <!-- Components definition (Layout) -->
     <!ELEMENT Components (Component*)>
     <!ELEMENT Component (Triggers?,Images*,Text*,Popup?,ProgressBar?)>
        <!ATTLIST Component Name CDATA #REQUIRED>
        <!ATTLIST Component Default CDATA #IMPLIED>
        <!ATTLIST Component Class CDATA #IMPLIED>
        <!ATTLIST Component Stretch CDATA #IMPLIED>
        <!ATTLIST Component Events CDATA #IMPLIED>
        <!ATTLIST Component Tooltip CDATA #IMPLIED>
        <!ATTLIST Component Accelerator CDATA #IMPLIED>
        <!ATTLIST Component Cursor CDATA #IMPLIED>
        <!ATTLIST Component ControlGroupId CDATA #IMPLIED>
        <!ATTLIST Component TooltipColor CDATA #IMPLIED>
        <!ATTLIST Component TooltipTextColor CDATA #IMPLIED>
        <!ATTLIST Component MouseOver CDATA #IMPLIED>
        <!ATTLIST Component DisabledTooltip CDATA #IMPLIED>
        <!ATTLIST Component WindowFocus CDATA #IMPLIED>
        <!ATTLIST Component Color CDATA #IMPLIED>
        <!ATTLIST Component Scrollbar CDATA #IMPLIED>
        <!ATTLIST Component PushType CDATA #IMPLIED>
        <!ATTLIST Component GroupId CDATA #IMPLIED>
        <!ATTLIST Component CaretColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionSelectorColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColorInActive CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColorInActive CDATA #IMPLIED>
 
    <!ELEMENT Triggers (Trigger*)>
    <!ELEMENT Trigger (#PCDATA)>
        <!ATTLIST Trigger Type (OnInit|OnAppStartRefreshServers|OnAppStopRefreshServers|OnDownloadComplete|OnActivate|OnDeactivate|OnLeftClick|OnRightClick|OnLeftButtonDown|OnRightButtonDown|OnLeftDoubleClick|OnRightDoubleClick|OnXfireUrlDownload) #IMPLIED>
  
    <!ELEMENT Images (Image*)>
        <!ATTLIST Images State (normal|hover|disabled|overlay) #IMPLIED>
        <!ATTLIST Images Color CDATA #IMPLIED>
        <!ATTLIST Images HeaderColor CDATA #IMPLIED>
        <!ATTLIST Images ColorShift CDATA #IMPLIED>
    
    <!ELEMENT Image (#PCDATA)>
        <!ATTLIST Image Type (topleft|top|topright|left|middle|right|bottomleft|bottom|bottomright|headerleft|headermiddle|headerright|headerarrowup|headerarrowdown|headercollapsed|headerexpanded) #IMPLIED>
    
    <!ELEMENT Popup (#PCDATA)>
        <!ATTLIST Popup SaveState CDATA #IMPLIED>

    <!ELEMENT ProgressBar (#PCDATA)>
        <!ATTLIST ProgressBar OutlineColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar BGColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar TextColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar Radius CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillRadius CDATA #IMPLIED>
    
    <!ELEMENT Text (#PCDATA)>
        <!ATTLIST Text Font CDATA #IMPLIED>
        <!ATTLIST Text State CDATA #IMPLIED>
        <!ATTLIST Text Size CDATA #IMPLIED>
        <!ATTLIST Text Bold CDATA #IMPLIED>
        <!ATTLIST Text Italic CDATA #IMPLIED>
        <!ATTLIST Text Background CDATA #IMPLIED>
        <!ATTLIST Text color_friend CDATA #IMPLIED>
        <!ATTLIST Text color_fof CDATA #IMPLIED>
        <!ATTLIST Text color_offline CDATA #IMPLIED>
        <!ATTLIST Text color_selected CDATA #IMPLIED>
        <!ATTLIST Text color_nonfocus CDATA #IMPLIED>
        <!ATTLIST Text color_selectedtext CDATA #IMPLIED>
        <!ATTLIST Text color_header CDATA #IMPLIED>
    
    <!ELEMENT Popups (Tile+)>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/SystemDialogs/Xig2AddFriend.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGAddFriend" Class="MainWindow" MinWidth="298" MinHeight="200" DefaultWidth="298" DefaultHeight="200" DefaultX="470" DefaultY="10">
        <Triggers>
            <Trigger Type="OnActiveMode">ShowTile</Trigger>
        </Triggers>
    </Component>
    
    <Component Name="XIGAddFriendTitle" Class="Text" Stretch="ToContent" Events="Transparent">
        <Text Align="Left" Font="Arial" Size="11" Bold="True" Color="XIGSystemDialogTitleCG">XIGAddFriendTitle</Text>
    </Component>
    
    <Component Name="XIGAddFriendUsernameText" Class="Text" MinHeight="14" Stretch="ToContent" Events="Transparent">
        <Text Font="Arial" Size="12" Bold="False" Color="XIGSystemDialogTextCG">XfireUsernameText</Text>
    </Component>
    
    <Component Name="XIGAddFriendUsernameEdit" Class="PrefEdit" MaxLength="64" Stretch="ToContent" ControlLabel="XfireUsername" CaretColor="XIGCaretCG" SelectionColor="ListColorSelectedCG" SelectionColor_InActive="TextFieldTextHighlightInactiveCG" SelectionTextColor="ListColorSelectedTextCG" SelectionSelectorColor="XIGCaretCG">
        <Fonts>
            <Font Type="Text" Font="Arial" Size="12" Bold="False" Color="ListFriendTextCG" />
        </Fonts>
    </Component>
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig/XigMainWindow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGMainWindow" Class="MainWindow" MinWidth="272" MinHeight="256">
        <Triggers>
            <Trigger Type="OnActiveMode">ShowTile</Trigger>
            <Trigger Type="OnInActiveMode">HideTile</Trigger>
            <Trigger Type="OnLeftButtonDown">AppDragWindow</Trigger>
        </Triggers>
        <Text Color_Personal="ChatPersonalNameCG" Color_PersonalText="ChatPersonalTextCG" Color_Other="ChatOtherNameCG" Color_OtherText="ChatOtherTextCG" />
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Window Frame
    //////////////////////////////////////////////
    -->
    <Component Name="XIGMainWindowTopRow" Class="Tile" MinHeight="13" MaxHeight="13" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="TopLeft">frame1_top_left</Image>
            <Image Type="Top">frame1_top_middle</Image>
            <Image Type="TopRight">frame1_top_right</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMainWindowLeftSide" Class="Tile" MinWidth="13" MaxWidth="13" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="Left">frame1_leftside_middle</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMainWindowBackground" Class="Tile" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="Middle">frame1_window_filler</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMainWindowRightSide" Class="Tile" MinWidth="13" MaxWidth="13" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="Right">frame1_rightside_middle</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMainWindowBottomRow" Class="Tile" MinHeight="13" MaxHeight="13" Stretch="ToContent" Default="Activate">
        <Images State="Normal">
            <Image Type="BottomLeft">frame1_bottom_left</Image>
            <Image Type="Bottom">frame1_bottom_middle</Image>
            <Image Type="BottomRight">frame1_bottom_right</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Content
    //////////////////////////////////////////////
    -->
    <Component Name="XIGMainWindowTitle" Class="Text" MinHeight="14" Stretch="ToContent">
        <Text Bold="True" Color="XIGActiveWindowTitleCG" Font="Arial" Size="11" />
    </Component>
    
    <Component Name="XIGMainWindowClock" Class="Text" MinWidth="28" MinHeight="14" Stretch="ToContent">
        <Text Bold="True" Color="XIGActiveWindowTitleCG" Font="Arial" Size="11" />
    </Component>
    
    <Component Name="XIGMainWindowChatArea" Class="Text" MinHeight="14" Stretch="ToContent">
        <Text Bold="False" Color="ListFriendTextCG" Font="Arial" Size="11" />
    </Component>
    
    <Component Name="XIGMainWindowChatEdit" Class="Text" MinHeight="18" Stretch="ToContent">
        <Text Color="ChatPersonalTextCG" Bold="False" Font="Arial" Size="11" />
    </Component>
    
    <Component Name="XIGMainWindowFooter" Class="Text" MinHeight="13" Stretch="ToContent">
        <Text Bold="True" Color="XIGActiveWindowTitleCG" Font="Arial" Size="11" />
    </Component>
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Strings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Strings SYSTEM "XfireSkin.dtd">

<Strings lang="en">
    <String Name="AdjustMicSensitivityTip" ResourceID="1073" />
    <String Name="AdjustMicSensitivyText" ResourceID="1073" />
    <String Name="AdjustMicVolumeText" ResourceID="1345" />
    <String Name="AdjustMicVolumeTip" ResourceID="1072" />
    <String Name="AdjustSpeakerVolumeText" ResourceID="1071" />
    <String Name="AdjustSpeakerVolumeTip" ResourceID="1071" />
    <String Name="AlertOptionsTitle" ResourceID="1278" />
    <String Name="AlwaysShowAlertText" ResourceID="1280" />
    <String Name="ButtonAddFriendTip" ResourceID="221" />
    <String Name="ButtonAddServersTip" ResourceID="265" />
    <String Name="ButtonAnswerCallTip" ResourceID="523" />
    <String Name="ButtonCallDisabledTip" ResourceID="746" />
    <String Name="ButtonCallTip" ResourceID="522" />
    <String Name="ButtonCancelCallTip" ResourceID="1104" />
    <String Name="ButtonChatFriendDisabledTip" ResourceID="423" />
    <String Name="ButtonChatFriendTip" ResourceID="222" />
    <String Name="ButtonChatRoomsTabTip" ResourceID="1289" />
    <String Name="ButtonCloseChatTip" ResourceID="1059" />
    <String Name="ButtonCloseDisabledTip" ResourceID="236" />
    <String Name="ButtonCloseTip" ResourceID="236" />
    <String Name="ButtonCreateChatRoomTip" ResourceID="1128" />
    <String Name="ButtonDeleteChatRoomTip" ResourceID="867" />
    <String Name="ButtonDeleteFilesDisabledTip" ResourceID="867" />
    <String Name="ButtonDeleteFilesTip" ResourceID="867" />
    <String Name="ButtonEnterChatRoomDisabledTip" ResourceID="1129" />
    <String Name="ButtonEnterChatRoomTip" ResourceID="1129" />
    <String Name="ButtonExpandInfoTip" ResourceID="232" />
    <String Name="ButtonFilesTabTip" ResourceID="288" />
    <String Name="ButtonFriendInfoDisabledTip" ResourceID="226" />
    <String Name="ButtonFriendInfoTip" ResourceID="226" />
    <String Name="ButtonFriendsTabTip" ResourceID="1065" />
    <String Name="ButtonGroupHostGameLobbyTip" ResourceID="768" />
    <String Name="ButtonGroupHostVoiceChatDisabledTip" ResourceID="746" />
    <String Name="ButtonGroupHostVoiceChatTip" ResourceID="744" />
    <String Name="ButtonGroupJoinVoiceChatTip" ResourceID="639" />
    <String Name="ButtonGroupLaunchGameLobbyTip" ResourceID="769" />
    <String Name="ButtonGroupLeaveGameLobbyTip" ResourceID="767" />
    <String Name="ButtonGroupLeaveVoiceChatTip" ResourceID="745" />
    <String Name="ButtonInfoPicturesTip" ResourceID="226" />
    <String Name="ButtonInviteUsersTip" ResourceID="798" />
    <String Name="ButtonJoinGameDisabledTip" ResourceID="393" />
    <String Name="ButtonJoinGameServersDisabledTip" ResourceID="147" />
    <String Name="ButtonJoinGameServersTip" ResourceID="147" />
    <String Name="ButtonJoinGameTip" ResourceID="224" />
    <String Name="ButtonLeaveCallTip" ResourceID="782" />
    <String Name="ButtonMaximizeTip" ResourceID="270" />
    <String Name="ButtonMaximizeDisabledTip" ResourceID="270" />
    <String Name="ButtonMinimizeDisabledTip" ResourceID="234" />
    <String Name="ButtonMinimizeTip" ResourceID="234" />
    <String Name="ButtonMuteMicDisabledTip" ResourceID="1283" />
    <String Name="ButtonMuteMicTip" ResourceID="524" />
    <String Name="ButtonNotificationsTabTip" ResourceID="1353" />
    <String Name="ButtonOpenFilesDisabledTip" ResourceID="322" />
    <String Name="ButtonOpenFilesTip" ResourceID="322" />
    <String Name="ButtonRefreshServersDisabledTip" ResourceID="263" />
    <String Name="ButtonRefreshServersTip" ResourceID="263" />
    <String Name="ButtonRetractInfoTip" ResourceID="233" />
    <String Name="ButtonScreenShotsTabTip" ResourceID="534" />
    <String Name="ButtonSearchFilesDisabledTip" ResourceID="390" />
    <String Name="ButtonSearchFilesTip" ResourceID="390" />
    <String Name="ButtonSearchVideosTip" ResourceID="1208" />
    <String Name="ButtonSendChatTip" ResourceID="435" />
    <String Name="ButtonServersTabTip" ResourceID="245" />
    <String Name="ButtonUnmuteMicTip" ResourceID="1407" />
    <String Name="ButtonUploadPicturesDisabledTip" ResourceID="1130" />
    <String Name="ButtonUploadTip" ResourceID="1130" />
    <String Name="ButtonUploadVideosDisabledTip" ResourceID="1130" />
    <String Name="ButtonVideosTabTip" ResourceID="1081" />
    <String Name="DisplayAlertOverlay" ResourceID="1074" />
    <String Name="DisplayBrowserOverlay" ResourceID="1231" />
    <String Name="DisplayClockOverlay" ResourceID="1075" />
    <String Name="DisplayDurationText" ResourceID="1281" />
    <String Name="DisplayDurationText" ResourceID="1281" />
    <String Name="DisplayFPSOverlay" ResourceID="1076" />
    <String Name="DisplayVoiceOverlay" ResourceID="1246" />
    <String Name="DisplayWebCamOverlay" ResourceID="1330" />
    <String Name="GCActionsMenu" ResourceID="436" />
    <String Name="GroupChatTitle" ResourceID="440" />
    <String Name="HelpMenu" ResourceID="231" />
    <String Name="ToolsMenu" ResourceID="229" />
    <String Name="TypingMessage" ResourceID="318" />
    <String Name="UserNameText" ResourceID="227" />
    <String Name="XIGAddFriendTitle" ResourceID="221" />
    <String Name="XIGAdjustOpacityTip" ResourceID="1056" />
    <String Name="XIGAllChatsView" ResourceID="1035" />
    <String Name="XIGBroadcastMicrophone" ResourceID="1351" />
    <String Name="XIGButtonCancelTip" ResourceID="201" />
    <String Name="XIGButtonChatsTabTip" ResourceID="1066" />
    <String Name="XIGButtonHelpTabTip" ResourceID="1064" />
    <String Name="XIGButtonOkTip" ResourceId="202" />
    <String Name="XIGButtonVoiceOptionsTabTip" ResourceID="1080" />
    <String Name="XIGChatRoomsTitle" ResourceID="452" />
    <String Name="XIGChatsTitle" ResourceID="1036" />
    <String Name="XIGEditModeOptionsTitle" ResourceID="1279" />
    <String Name="XIGFPSText" ResourceID="1077" />
    <String Name="XIGFriendsTitle" ResourceID="244" />
    <String Name="XIGHelpTitle" ResourceID="347" />
    <String Name="XIGMusicButtonMuteTip" ResourceID="1345" />
    <String Name="XIGOptionsTitle" ResourceID="1152" />
    <String Name="XIGRecordLiveVideoText" ResourceID="1331" />
    <String Name="XIGRoomInviteInstructions" ResourceID="1088" />
    <String Name="XIGRoomInviteTitle" ResourceID="798" />
    <String Name="XIGVoiceOptionsTip" ResourceID="1290" />
    <String Name="XIGWebButtonBackTip" ResourceID="1237" />
    <String Name="XIGWebButtonForwardTip" ResourceID="1236" />
    <String Name="XIGWebButtonHomeTip" ResourceID="1063" />
    <String Name="XIGWebButtonNewTabTip" ResourceID="1241" />
    <String Name="XIGWebButtonRefreshTip" ResourceID="1235" />
    <String Name="XIGWebSearchEditTip" ResourceID="1233" />
    <String Name="XfireMenu" ResourceID="228" />
    <String Name="XfireUsernameText" ResourceID="391" />
</Strings>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/SystemDialogs/Xig2AlertOpt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGAlertOptions" Class="MainWindow" MinWidth="298" MinHeight="225" DefaultWidth="298" DefaultHeight="225" DefaultX="470" DefaultY="10">
        <Triggers>
            <Trigger Type="OnActiveMode">ShowTile</Trigger>
        </Triggers>
    </Component>
    
    <Component Name="XIGAlertOptionsTitle" Class="Text" Stretch="ToContent" Events="Transparent">
        <Text Align="Left" Font="Arial" Size="11" Bold="True" Color="XIGSystemDialogTitleCG">AlertOptionsTitle</Text>
    </Component>
    
    <Component Name="XIGAlertOptionsPermanentCheckBox" Class="PrefCheckbox" MinWidth="16" MaxWidth="16" MinHeight="16" MaxHeight="16" Stretch="ToContent" DrawOnTopMost="True" ControlLabel="AlertPermanent">
        <Images State="Normal">
            <Image Type="Middle">button_checkbox_unchecked</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_checkbox_checked</Image>
        </Images>
    </Component>
    
    <Component Name="XIGAlertOptionsPermanentText" Class="Text" MinHeight="13" Stretch="ToContent">
        <Text Font="Arial" Size="12" Bold="False" Color="XIGSystemDialogTextCG">AlwaysShowAlertText</Text>
    </Component>
    
    <Component Name="XIGAlertOptionsDurationEdit" MinHeight="17" MinWidth="60" Class="PrefEdit" Stretch="ToContent" CaretColor="XIGCaretCG" SelectionColor="ListColorSelectedCG" SelectionTextColor="ListColorSelectedTextCG" SelectionSelectorColor="XIGCaretCG" ControlLabel="AlertDuration" Numeric="True">
        <Fonts>
            <Font Type="Text" Font="Arial" Size="12" Bold="False" Color="TextFieldTextCG" />
        </Fonts>
    </Component>
    
    <Component Name="XIGAlertOptionsDurationEditBackground" Class="Tile" MinHeight="19" MinWidth="62" Stretch="ToContent" Default="Activate" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">text_top_left</Image>
            <Image Type="Top">text_top_middle</Image>
            <Image Type="TopRight">text_top_right</Image>
            <Image Type="Left">text_leftside_middle</Image>
            <Image Type="Middle">text_middle</Image>
            <Image Type="Right">text_rightside_middle</Image>
            <Image Type="BottomLeft">text_bottom_left</Image>
            <Image Type="Bottom">text_bottom_middle</Image>
            <Image Type="BottomRight">text_bottom_right</Image>
        </Images>
    </Component>
    
    <Component Name="XIGAlertOptionsDurationText" Class="Text" Stretch="ToContent">
        <Text Font="Arial" Size="12" Bold="False" Color="XIGSystemDialogTextCG">DisplayDurationText</Text>
    </Component>
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Popups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <!--
    //////////////////////////////////////////////
    // Window Frame
    //////////////////////////////////////////////
    -->
    <!-- This is what hides the Info View Out button -->
    <!-- <Component Name="InfoViewButtonMask" Class="Tile" MinWidth="75" MaxWidth="75" Stretch="ToContent" Default="Activate" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">frame2_mask_top</Image>
            <Image Type="Left">frame2_mask_middle</Image>
            <Image Type="BottomLeft">frame2_mask_bottom</Image>
        </Images>
    </Component> -->
    
    <!-- <Component Name="ChatInfoViewButtonMask" Class="Tile" MinWidth="27" MaxWidth="27" Stretch="ToContent" Default="Activate" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">frame2_mask_top</Image>
            <Image Type="Left">frame2_mask_middle</Image>
            <Image Type="BottomLeft">frame2_chat_mask_bottom</Image>
        </Images>
    </Component> -->
    
    <Component Name="InfoViewTopRow" Class="Tile" MinHeight="19" MaxHeight="19" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="TopLeft">frame2_top_left</Image>
            <Image Type="Top">frame2_top_middle</Image>
            <Image Type="TopRight">frame2_top_right</Image>
        </Images>
    </Component>
    
    <Component Name="InfoViewLeftSide" Class="Tile" MinWidth="19" MaxWidth="19" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="Left">frame2_leftside_middle</Image>
        </Images>
    </Component>
    
    <Component Name="InfoViewBackground" Class="Tile" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="Middle">frame2_window_filler</Image>
        </Images>
    </Component>
    
    <Component Name="InfoViewRightSide" Class="Tile" MinWidth="19" MaxWidth="19" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="Right">frame2_rightside_middle</Image>
        </Images>
    </Component>
    
    <Component Name="InfoViewBottomRow" Class="Tile" MinHeight="19" MaxHeight="19" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="BottomLeft">frame2_bottom_left</Image>
            <Image Type="Bottom">frame2_bottom_middle</Image>
            <Image Type="BottomRight">frame2_bottom_right</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Resize Grippers
    //////////////////////////////////////////////
    -->
    <Component Name="PopupResizeGripperR" Class="Tile" MinWidth="10" MaxWidth="10" Cursor="ResizeWE">
        <Triggers>
            <Trigger Type="OnLeftButtonDown">ResizeR</Trigger>
        </Triggers>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Main Window
    //////////////////////////////////////////////
    -->
    <Component Name="MainInfoViewPopup" Class="Tile" MinWidth="196" MinHeight="385" DefaultWidth="196" BindX="False" BindY="True" ResizeY="100" />
    
    <Component Name="MainInfoViewContent" Class="InfoView" Color="InfoViewBGCG" Scrollbar="XfireScrollbar">
        <Text Font="Arial" Size="11" Color="InfoViewTextCG" Color_FoF="ListFoFTextCG" Color_Friend="ListFriendTextCG" Color_Offline="ListOfflineTextCG" Color_Hyperlink="LinkTextCG" />
    </Component>
    
    <Component Name="MainInfoViewWebSearchEdit" Class="WebSearchEditView" MinWidth="118" MinHeight="16" ToolTip="WebSearchTip">
        <Text Font="Arial" Size="11" Color="RoomNameEditTextCG" Align="Left" Background="RoomNameEditBGCG">StatusText</Text>
    </Component>    
    
    
    
    <!--
    //////////////////////////////////////////////
    // Chat Window
    //////////////////////////////////////////////
    -->
    <Component Name="ChatInfoViewPopup" Class="Tile" MinWidth="196" DefaultWidth="196" BindX="False" BindY="True" ResizeY="100" />
    
    <Component Name="ChatInfoViewContent" Class="InfoView" Color="InfoViewBGCG" Scrollbar="XfireScrollbar">
        <Text Font="Arial" Size="11" Color="InfoViewTextCG" Color_FoF="ListFoFTextCG" Color_Friend="ListFriendTextCG" Color_Offline="ListOfflineTextCG" Color_Hyperlink="LinkTextCG" />
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // XIG Tooltip
    //////////////////////////////////////////////
    -->
    <Component Name="XIGToolTip" Class="ToolTip" Stretch="ToContent" Color="ToolTipBGCG">
        <Text Font="Arial" Size="11" Color="ToolTipTextCG" Indent="3">%s</Text>
    </Component>
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SkinDescription SYSTEM "XfireSkin.dtd">

<SkinDescription>
    <Author Type="Original">Xfire, Inc.</Author>
    <Author Type="Contributor">Xfire, Inc.</Author>
    <Website>http://www.xfire.com/</Website>
    <Name>Symbiosis</Name>
    <LongName>Symbiosis</LongName>
    <Version>1.0</Version>
    <CompatibleVersion>1.58</CompatibleVersion>
</SkinDescription>
