=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/XfireSkin.dtd
<!ELEMENT XfireSkin (SkinDescription,GlobalPrefs?,Strings+,Themes?,Components,MainSkin,ChatSkin,GroupChatSkin,InGameMainSkin,InGameAlertSkin,Popups?)>
 
     <!-- SkinsDescription definition -->
     <!ELEMENT SkinDescription (Author*,Website?,Name,LongName,Version,CompatibleVersion,License?)>
     <!ELEMENT Author (#PCDATA)>
        <!ATTLIST Author Type (original|contributor) "original">
     <!ELEMENT Website (#PCDATA)>
     <!ELEMENT Name (#PCDATA)>
     <!ELEMENT LongName (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT CompatibleVersion (#PCDATA)>
     <!ELEMENT License (#PCDATA)>
 
     <!-- GlobalPrefs definition -->
     <!ELEMENT GlobalPrefs (TooltipColor?,TooltipTextColor?,OnlineSound?,OfflineSound?)>
     <!ELEMENT TooltipColor (#PCDATA)>
     <!ELEMENT TooltipTextColor (#PCDATA)>
     <!ELEMENT OnlineSound (#PCDATA)>
     <!ELEMENT OfflineSound (#PCDATA)>
 
     <!-- Strings definition -->
     <!ELEMENT Strings (String*)>
        <!ATTLIST Strings Lang CDATA "default">
     <!ELEMENT String (#PCDATA)>
        <!ATTLIST String Name CDATA #REQUIRED>
        <!ATTLIST String ResourceId CDATA #IMPLIED>
 
     <!-- Themes definition -->
     <!ELEMENT Themes (Theme*)>
     <!ELEMENT Theme (Colors?,ColorShifts?,Sounds?,Bitmaps?)>
 
     <!ELEMENT Colors (Color*)>
     <!ELEMENT Color (#PCDATA)>
        <!ATTLIST Color Red CDATA #IMPLIED>
        <!ATTLIST Color Green CDATA #IMPLIED>
        <!ATTLIST Color Blue CDATA #IMPLIED>
        <!ATTLIST Color Alpha CDATA #IMPLIED>
 
     <!ELEMENT ColorShifts (ColorShift*)>
     <!ELEMENT ColorShift (#PCDATA)>
        <!ATTLIST ColorShift Red CDATA #IMPLIED>
        <!ATTLIST ColorShift Green CDATA #IMPLIED>
        <!ATTLIST ColorShift Blue CDATA #IMPLIED>
        <!ATTLIST ColorShift Alpha CDATA #IMPLIED>
 
     <!ELEMENT Sounds (Sound*)>
     <!ELEMENT Sound (#PCDATA)>
        <!ATTLIST Sound Name CDATA #REQUIRED>
        <!ATTLIST Sound ResourceId CDATA #IMPLIED>
 
     <!ELEMENT Bitmaps (Bitmap*)>
     <!ELEMENT Bitmap (#PCDATA)>
        <!ATTLIST Bitmap Name CDATA #REQUIRED>
        <!ATTLIST Bitmap ResourceId CDATA #IMPLIED>
 
     <!-- Window definitions -->
     <!ELEMENT MainSkin (Tile)>
     <!ELEMENT ChatSkin (Tile)>
     <!ELEMENT GroupChatSkin (Tile)>
     <!ELEMENT InGameAlertSkin (Tile)>
     <!ELEMENT InGameMainSkin (Tile)>
 
     <!-- Tiles definition (Layout) -->
     <!ELEMENT Tile (Tile*)>
        <!ATTLIST Tile Name CDATA #REQUIRED>
        <!ATTLIST Tile AlignX (left|center|right) #IMPLIED>
        <!ATTLIST Tile AlignY (top|center|bottom) #IMPLIED>
        <!ATTLIST Tile Top CDATA #IMPLIED>
        <!ATTLIST Tile Left CDATA #IMPLIED>
        <!ATTLIST Tile Bottom CDATA #IMPLIED>
        <!ATTLIST Tile Right CDATA #IMPLIED>
        <!ATTLIST Tile Width CDATA #IMPLIED>
        <!ATTLIST Tile Height CDATA #IMPLIED>
        <!ATTLIST Tile Component CDATA #REQUIRED>
        <!ATTLIST Tile MinWidth CDATA #IMPLIED>
        <!ATTLIST Tile MinHeight CDATA #IMPLIED>
        <!ATTLIST Tile DefaultWidth CDATA #IMPLIED>
        <!ATTLIST Tile DefaultHeight CDATA #IMPLIED>
        <!ATTLIST Tile ResizeX CDATA #IMPLIED>
        <!ATTLIST Tile ResizeY CDATA #IMPLIED>
        <!ATTLIST Tile X CDATA #IMPLIED>
        <!ATTLIST Tile Y CDATA #IMPLIED>
        <!ATTLIST Tile Z CDATA #IMPLIED>
        <!ATTLIST Tile IndentLeft CDATA #IMPLIED>
        <!ATTLIST Tile IndentRight CDATA #IMPLIED>
        <!ATTLIST Tile IndentTop CDATA #IMPLIED>
        <!ATTLIST Tile IndentBottom CDATA #IMPLIED>
        <!ATTLIST Tile JustX CDATA #IMPLIED>
        <!ATTLIST Tile JustY CDATA #IMPLIED>
        <!ATTLIST Tile BindX CDATA #IMPLIED>
        <!ATTLIST Tile BindY CDATA #IMPLIED>
        <!ATTLIST Tile OutdentLeft CDATA #IMPLIED>
        <!ATTLIST Tile OutdentRight CDATA #IMPLIED>
        <!ATTLIST Tile OutdentTop CDATA #IMPLIED>
        <!ATTLIST Tile OutdentBottom CDATA #IMPLIED>

     <!-- Components definition (Layout) -->
     <!ELEMENT Components (Component*)>
     <!ELEMENT Component (Triggers?,Images*,Text*,Popup?,ProgressBar?)>
        <!ATTLIST Component Name CDATA #REQUIRED>
        <!ATTLIST Component Default CDATA #IMPLIED>
        <!ATTLIST Component Class CDATA #IMPLIED>
        <!ATTLIST Component Stretch CDATA #IMPLIED>
        <!ATTLIST Component Events CDATA #IMPLIED>
        <!ATTLIST Component Tooltip CDATA #IMPLIED>
        <!ATTLIST Component Accelerator CDATA #IMPLIED>
        <!ATTLIST Component Cursor CDATA #IMPLIED>
        <!ATTLIST Component ControlGroupId CDATA #IMPLIED>
        <!ATTLIST Component TooltipColor CDATA #IMPLIED>
        <!ATTLIST Component TooltipTextColor CDATA #IMPLIED>
        <!ATTLIST Component MouseOver CDATA #IMPLIED>
        <!ATTLIST Component DisabledTooltip CDATA #IMPLIED>
        <!ATTLIST Component WindowFocus CDATA #IMPLIED>
        <!ATTLIST Component Color CDATA #IMPLIED>
        <!ATTLIST Component Scrollbar CDATA #IMPLIED>
        <!ATTLIST Component PushType CDATA #IMPLIED>
        <!ATTLIST Component GroupId CDATA #IMPLIED>
        <!ATTLIST Component CaretColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionSelectorColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionColorInActive CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColor CDATA #IMPLIED>
        <!ATTLIST Component SelectionTextColorInActive CDATA #IMPLIED>
 
    <!ELEMENT Triggers (Trigger*)>
    <!ELEMENT Trigger (#PCDATA)>
        <!ATTLIST Trigger Type (OnInit|OnAppStartRefreshServers|OnAppStopRefreshServers|OnDownloadComplete|OnActivate|OnDeactivate|OnLeftClick|OnRightClick|OnLeftButtonDown|OnRightButtonDown|OnLeftDoubleClick|OnRightDoubleClick|OnXfireUrlDownload) #IMPLIED>
  
    <!ELEMENT Images (Image*)>
        <!ATTLIST Images State (normal|hover|disabled|overlay) #IMPLIED>
        <!ATTLIST Images Color CDATA #IMPLIED>
        <!ATTLIST Images HeaderColor CDATA #IMPLIED>
        <!ATTLIST Images ColorShift CDATA #IMPLIED>
    
    <!ELEMENT Image (#PCDATA)>
        <!ATTLIST Image Type (topleft|top|topright|left|middle|right|bottomleft|bottom|bottomright|headerleft|headermiddle|headerright|headerarrowup|headerarrowdown|headercollapsed|headerexpanded) #IMPLIED>
    
    <!ELEMENT Popup (#PCDATA)>
        <!ATTLIST Popup SaveState CDATA #IMPLIED>

    <!ELEMENT ProgressBar (#PCDATA)>
        <!ATTLIST ProgressBar OutlineColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar BGColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar TextColor CDATA #IMPLIED>
        <!ATTLIST ProgressBar Radius CDATA #IMPLIED>
        <!ATTLIST ProgressBar FillRadius CDATA #IMPLIED>
    
    <!ELEMENT Text (#PCDATA)>
        <!ATTLIST Text Font CDATA #IMPLIED>
        <!ATTLIST Text State CDATA #IMPLIED>
        <!ATTLIST Text Size CDATA #IMPLIED>
        <!ATTLIST Text Bold CDATA #IMPLIED>
        <!ATTLIST Text Italic CDATA #IMPLIED>
        <!ATTLIST Text Background CDATA #IMPLIED>
        <!ATTLIST Text color_friend CDATA #IMPLIED>
        <!ATTLIST Text color_fof CDATA #IMPLIED>
        <!ATTLIST Text color_offline CDATA #IMPLIED>
        <!ATTLIST Text color_selected CDATA #IMPLIED>
        <!ATTLIST Text color_nonfocus CDATA #IMPLIED>
        <!ATTLIST Text color_selectedtext CDATA #IMPLIED>
        <!ATTLIST Text color_header CDATA #IMPLIED>
    
    <!ELEMENT Popups (Tile+)>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/ChatWindow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tile SYSTEM "XfireSkin.dtd">

<Tile Name="StandardChatWindow" ResizeX="100" ResizeY="100" Component="ChatMainWindow">
    <!--
    //////////////////////////////////////////////
    // Resize Grippers
    //////////////////////////////////////////////
    -->
    <Tile Name="ResizeGripperTL" Z="26" JustX="Left" JustY="Top" Component="ChatResizeGripperTL" />
    <Tile Name="ResizeTop" Z="25" ResizeX="100" IndentLeft="ResizeGripperTL.Width" IndentRight="ResizeGripperTR.Width+13" Component="ChatResizeGripperTop" />
    <Tile Name="ResizeGripperTR" X="13" Z="26" JustX="Right" JustY="Top" Component="ChatResizeGripperTR" />
    <Tile Name="ResizeL" Z="25" ResizeY="100" IndentTop="ResizeGripperTL.Height" IndentBottom="ResizeGripperBL.Height" Component="ChatResizeGripperL" />
    <Tile Name="ResizeR" X="13" Z="25" JustX="Right" ResizeY="100" IndentTop="ResizeGripperTR.Height" IndentBottom="ResizeGripperBR.Height" Component="ChatResizeGripperR" />
    <Tile Name="ResizeGripperBL" Z="26" JustX="Left" JustY="Bottom" Component="ChatResizeGripperBL" />
    <Tile Name="ResizeBottom" Z="25" JustX="Center" JustY="Bottom" ResizeX="100" IndentLeft="ResizeGripperBL.Width" IndentRight="ResizeGripperBR.Width+13" Component="ChatResizeGripperBottom" />
    <Tile Name="ResizeGripperBR" X="13" Z="26" JustX="Right" JustY="Bottom" Component="ChatResizeGripperBR" />
    
    
    
    <!--
    //////////////////////////////////////////////
    // Window Draggers
    //////////////////////////////////////////////
    -->
    <Tile Name="WindowDraggerTop" Z="10" ResizeX="100" ResizeY="100" IndentRight="13" Component="WindowDragger" />
    
    
    
    <!--
    //////////////////////////////////////////////
    // Window Frame
    //////////////////////////////////////////////
    -->
    <Tile Name="TopRow" Z="1" ResizeX="100" IndentRight="13" Component="ChatTopRow" />
    <Tile Name="LeftSide" Z="1" JustX="Left" ResizeY="100" IndentTop="TopRow.Height" IndentBottom="BottomRow.Height" Component="ChatLeftSide" />
    <Tile Name="Background" Z="1" ResizeX="100" ResizeY="100" IndentTop="TopRow.Height" IndentRight="RightSide.Width+13" IndentBottom="BottomRow.Height" IndentLeft="LeftSide.Width" Component="ChatBackground" />
    <Tile Name="RightSide" X="13" Z="1" JustX="Right" ResizeY="100" IndentTop="TopRow.Height" IndentBottom="BottomRow.Height" Component="ChatRightSide" />
    <Tile Name="BottomRow" Z="1" JustY="Bottom" ResizeX="100" IndentRight="13" Component="ChatBottomRow" />
    
    
    
    <!--
    //////////////////////////////////////////////
    // Content
    //////////////////////////////////////////////
    -->
    <!--[BEGIN] Info Bar -->
    <Tile Name="InfoBar" Y="5" Z="24" ResizeX="100" IndentLeft="5" IndentRight="18" Component="InfoBar">
        <!--[BEGIN] Xfire Logo -->
        <!-- <Tile Name="XfireLogo" X="65" Y="2" Z="99" Component="XfireLogoNoLink" /> -->
        <!--[END] Xfire Logo -->
        
        
        <!--[BEGIN] Username -->
        <Tile Name="ChatUserContainer" X="4" Y="5" ResizeX="100" IndentRight="93" Component="ChatUserContainer">
            <Tile Name="TabbedTalkingState" Z="26" JustY="Center" Component="TabbedTalkingState">
                <Tile Name="ButtonNotTalking" Z="26" JustX="Center" JustY="Center" Component="ChatButtonNotTalking" />
                <Tile Name="ButtonTalking" Z="26" JustX="Center" JustY="Center" Component="ChatButtonTalking" />
            </Tile>
            <Tile Name="ChatUser" X="TabbedTalkingState.Right+2" Z="26" JustY="Center" Component="ChatUser" />
        </Tile>
        <!--[END] Username -->
        
        
        <!--[BEGIN] Window Control -->
        <Tile Name="ButtonMinimize" X="49" Y="3" Z="25" JustX="Right" Component="ButtonMinimize" />
        <Tile Name="ButtonMaximize" X="25" Y="3" Z="25" JustX="Right" Component="ButtonMaximize" />
        <Tile Name="ButtonClose" X="5" Y="3" Z="25" JustX="Right" Component="ButtonClose" />
        <!--[END] Window Control -->
    </Tile>
    <!--[END] Info Bar -->
    
    
    <!--[BEGIN] Menus -->
    <Tile Name="MenuBackground" Y="InfoBar.Bottom+1" Z="24" ResizeX="100" IndentLeft="5" IndentRight="18" Component="MenuBackground">
        <Tile Name="XfireMenu" X="3" Z="25" Component="XfireMenu" />
        <Tile Name="ActionsMenu" X="XfireMenu.Right+2" Z="25" Component="ActionsMenu" />
        <Tile Name="HelpMenu" X="ActionsMenu.Right+2" Z="35" Component="HelpMenu" />
    </Tile>
    <!--[END] Menus -->
    
    
    <!--
    //////////////////////////////////////////////
    // Chat Area & Chat Edit
    //////////////////////////////////////////////
    -->
    <Tile Name="ChatContainer" Y="MenuBackground.Bottom+1" Z="24" ResizeX="100" ResizeY="100" IndentRight="18" IndentBottom="122" IndentLeft="5" Component="ContentContainer">
        <!--[BEGIN] Chat Area -->
        <Tile Name="ChatArea" Z="25" ResizeX="100" ResizeY="100" IndentRight="2" IndentBottom="2" IndentLeft="2" IndentTop="2" Component="ChatArea" />
        <!--[END] Chat Area -->
    </Tile>
    
    
    <!--[BEGIN] Typing Message -->
    <Tile Name="ChatTypingMessage" X="4" Y="ChatContainer.Bottom" Z="25" ResizeX="100" IndentRight="18" IndentLeft="5" Component="ChatTypingMessage" />
    <!--[END] Typing Message -->
    
    <!-- <Tile Name="ChatSeparator" Y="ChatContainer.Bottom+2" Z="24" ResizeX="100" IndentRight="27" IndentLeft="15" Component="HorizontalSeparator" /> -->
    
    <!--[BEGIN] Chat Edit -->
    <Tile Name="ChatEditContentContainer" Y="ChatTypingMessage.Bottom" Z="24" ResizeX="100" ResizeY="100" IndentRight="18" IndentBottom="51" IndentLeft="6" Component="TextContainer">
        <Tile Name="ChatEditBG" Z="24" ResizeX="100" ResizeY="100" IndentRight="55" IndentBottom="4" IndentLeft="4" IndentTop="4" Component="ChatEditContainer">
            <Tile Name="ChatEdit" Z="25" ResizeX="100" ResizeY="100" Component="ChatEdit" />
        </Tile>
        <Tile Name="ButtonSend" X="ChatEditBG.Right" Y="2" Z="30" Component="ChatButtonSend" />
    </Tile>
    <!--[END] Chat Edit -->
    
    
    
    <!--
    //////////////////////////////////////////////
    // Buttons
    //////////////////////////////////////////////
    -->
    <Tile Name="ButtonBar" Y="ChatEditContentContainer.Bottom+1" Z="25" ResizeX="100" ResizeY="100" IndentRight="18" IndentLeft="5" Component="ChatButtonBar">
        <Tile Name="TabbedCall" X="1" Y="1" Z="25" Component="TabbedCall">
            <Tile Name="ChatButtonCall" Z="25" JustX="Center" JustY="Center" Component="ChatButtonCall" />
            <Tile Name="ChatButtonAnswerCall" Z="25" JustX="Center" JustY="Center" Component="ChatButtonAnswerCall" />
            <Tile Name="ChatButtonCancelCall" Z="25" JustX="Center" JustY="Center" Component="ChatButtonCancelCall" />
            <Tile Name="ChatButtonLeaveCall" Z="25" JustX="Center" JustY="Center" Component="ChatButtonLeaveCall" />
        </Tile>
        <Tile Name="Separator1" X="TabbedCall.Right" Component="ButtonBarVerticalSeparator" />
        <!-- TabbedMute and TabbedTalkingState overlap each other. TabbedTalkingState
              has a higher Z-Index -->
        <Tile Name="TabbedMute" X="Separator1.Right" Y="TabbedCall.Top" Z="25" Component="TabbedMute">
            <Tile Name="ButtonMute" Z="25" JustX="Center" JustY="Center" Component="ChatButtonMuteSelf" />
            <Tile Name="ButtonUnmute" Z="25" JustX="Center" JustY="Center" Component="ChatButtonUnmuteSelf" />
        </Tile>
        <Tile Name="Separator2" X="TabbedMute.Right" Component="ButtonBarVerticalSeparator" />
        <Tile Name="ButtonJoinGame" X="Separator2.Right" Y="TabbedCall.Top" Z="25" Component="ChatButtonJoin" />
        <Tile Name="Separator3" X="ButtonJoinGame.Right" Component="ButtonBarVerticalSeparator" />
        <Tile Name="ButtonInfo" X="Separator3.Right" Y="TabbedCall.Top" Z="25" Component="ButtonInfo" />
        <Tile Name="Separator4" X="ButtonInfo.Right" Component="ButtonBarVerticalSeparator" />
    </Tile>
    
    
    <!--[BEGIN] Info View -->
    <Tile Name="ChatInfoViewButton" Z="30" JustX="Right" JustY="Center" Component="ButtonChatInfoOut" />
    <!--[END] Info View -->
</Tile>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/Overlays/Xig2Music.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGMusicPlayerWindow" Class="MainWindow" MinWidth="306" MinHeight="200" DefaultWidth="306" DefaultHeight="200" DefaultX="470" DefaultY="300">
        <Triggers>
            <Trigger Type="OnActiveMode">ShowTile</Trigger>
        </Triggers>
    </Component>
    
    <Component Name="XIGMusicPlayerTitle" Class="Text" MinHeight="14" Stretch="ToContent" Events="Transparent">
        <Text Font="Arial" Size="12" Bold="True" Color="XIGOverlayTitleCG">%music_player_type%</Text>
    </Component>
    
    <Component Name="XIGMusicPlayerCurrentTrack" Class="Text" MinHeight="14" Stretch="ToContent" Events="Transparent">
        <Text Font="Arial" Size="10" Bold="False" Color="XIGMusicPlayerTrackTextCG">%music_current_track%</Text>
    </Component>
    
    <Component Name="XIGMusicPlayerTrackArtistDivider" Class="Text" MinHeight="14" Stretch="ToContent" Events="Transparent">
        <Text Font="Arial" Size="10" Bold="False" Color="XIGMusicPlayerTrackTextCG">--</Text>
    </Component>
    
    <Component Name="XIGMusicPlayerCurrentArtist" Class="Text" MinHeight="14" Stretch="ToContent" Events="Transparent">
        <Text Font="Arial" Size="10" Bold="False" Color="XIGMusicPlayerTrackTextCG">%music_current_artist%</Text>
    </Component>
    
    <!-- Music player playlist header then playlist text -->
    <Component Name="XIGMusicPlayerPlaylistHeader" Class="Tile" MinHeight="20" MaxHeight="20" Stretch="ToContent">
        <Images State="Normal">
            <Image Type="Left">header_left</Image>
            <Image Type="Middle">header_middle</Image>
            <Image Type="Right">header_right</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerPlaylistHeaderText" Class="Text" MinHeight="14" Stretch="ToContent">
        <Text Font="Arial" Size="10" Bold="True" Color="HeaderTextCG">Now Playing: </Text>
    </Component>
    
    <!-- Music player playlist -->
    <Component Name="XIGMusicPlayerPlaylist" Class="MusicPlaylist" ToolTipTile="XIGToolTipPopup" SelectedFocusColor="ListColorSelectedTextCG" HasIcons="False">
        <Fonts>
            <Font Type="DisplayName" Font="Arial" Size="10" Bold="False" Italics="False" Color="ListFriendTextCG" />
            <Font Type="SelectedDisplayName" Font="Arial" Size="10" Bold="True" Italics="False" Color="ListColorSelectedTextCG" />
        </Fonts>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Buttons
    //////////////////////////////////////////////
    -->
    <Component Name="XIGMusicPlayerControlsContainer" Class="Tile" MinHeight="16" MaxHeight="16" Stretch="ToContent" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">button_bar_left_small</Image>
            <Image Type="Top">button_bar_middle_small</Image>
            <Image Type="TopRight">button_bar_right_small</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerButtonPrevTrack" Class="MusicButtonPrevious" MinWidth="32" MaxWidth="32" MinHeight="14" MaxHeight="14" Stretch="ToContent" ToolTipTile="XIGToolTipPopup" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">button_xig_music_previous_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_xig_music_previous_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_xig_music_previous_down</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerButtonNextTrack" Class="MusicButtonNext" MinWidth="32" MaxWidth="32" MinHeight="14" MaxHeight="14" Stretch="ToContent" ToolTipTile="XIGToolTipPopup" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">button_xig_music_next_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_xig_music_next_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_xig_music_next_down</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerButtonPlayPauseTrack" Class="MusicButtonPlayPause" MinWidth="32" MaxWidth="33" MinHeight="14" MaxHeight="14" Stretch="ToContent" ToolTipTile="XIGToolTipPopup" DrawOnTopMost="True" />
    
    <Component Name="XIGMusicPlayerButtonPlayTrack" Class="Tile" MinWidth="32" MaxWidth="32" MinHeight="14" MaxHeight="14" Stretch="ToContent" Events="Transparent" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">button_xig_music_play_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_xig_music_play_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_xig_music_play_down</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerButtonPauseTrack" Class="Tile" MinWidth="33" MaxWidth="33" MinHeight="14" MaxHeight="14" Stretch="ToContent" Events="Transparent" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">button_xig_music_pause_norm</Image>
        </Images>
        <Images State="Hover">
            <Image Type="Middle">button_xig_music_pause_hover</Image>
        </Images>
        <Images State="Down">
            <Image Type="Middle">button_xig_music_pause_down</Image>
        </Images>
    </Component>
    
    <!-- Music player volume control, and its child tiles that serve as the image for the button -->
    <Component Name="XIGMusicPlayerVolume" Class="VolumeControl" MinWidth="93" MinHeight="14" MaxHeight="14" Stretch="ToContent" ToolTip="XIGMusicButtonMuteTip" ToolTipTile="XIGToolTipPopup" Type="MusicVolume" />
    
    <Component Name="XIGMusicPlayerVolumeMute" Class="Tile" MinWidth="39" MaxWidth="39" MinHeight="14" MaxHeight="14" Stretch="ToContent" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">button_xig_music_mute_norm</Image>
        </Images>
    </Component>
    
    <Component Name="XIGMusicPlayerVolumeBar" Class="Tile" MinWidth="1" MaxWidth="1" MinHeight="7" MaxHeight="7" Stretch="ToContent" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="Middle">xig_music_volume_bar_on</Image>
        </Images>
        <Images State="Disabled">
            <Image Type="Middle">xig_music_volume_bar_off</Image>
        </Images>
    </Component>
    
    <!-- <Component Name="XIGMusicPlayerVolumeBackground" Class="Tile" MinWidth="93" MaxWidth="93" MinHeight="11" MaxHeight="11" Stretch="ToContent" DrawOnTopMost="True">
        <Images State="Normal">
            <Image Type="TopLeft">xig_music_volume_background_left</Image>
            <Image Type="Top">xig_music_volume_background_middle</Image>
            <Image Type="TopRight">xig_music_volume_background_right</Image>
        </Images>
    </Component> -->
    
    <!-- <Component Name="XIGMusicPlayerVolumeBarOverlay" Class="Tile" MinWidth="90" MaxWidth="90" MinHeight="12" MaxHeight="12" Stretch="ToContent" DrawOnTopMost="True" Events="Transparent">
        <Images State="Normal">
            <Image Type="Middle">xig_music_volume_bar_overlay</Image>
        </Images>
    </Component> -->
</Components>

=== ScopeCreep-zip/Rekindle/unpacked/skins_extracted/Components/Xig2/ActiveWindows/Xig2Help.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Components SYSTEM "XfireSkin.dtd">

<Components>
    <Component Name="XIGHelp" Class="MainWindow" MinWidth="393" MinHeight="323" DefaultWidth="393" DefaultHeight="323" DefaultX="10" DefaultY="10">
        <Triggers>
            <Trigger Type="OnShowHelp">ShowWindow</Trigger>
        </Triggers>
    </Component>
    
    <Component Name="XIGHelpTitle" Class="Text" Stretch="ToContent" Events="Transparent" DrawOnTopMost="False">
        <Text Align="Left" Font="Arial" Size="11" Bold="True" Color="XIGActiveWindowTitleCG">XIGHelpTitle</Text>
    </Component>
    
    <Component Name="XIGHelpText" Class="HelpText" Stretch="ToContent" DrawOnTopMost="False">
        <Fonts>
            <Font Type="UserLink" Font="Arial" Size="11" Bold="True" Color="LinkTextCG" />
            <Font Type="User" Font="Arial" Size="11" Bold="False" Color="ListFriendTextCG" />
        </Fonts>
        <Images State="UserIcon">
            <Image Type="Middle">icon_chat</Image>
        </Images>
        <Images State="UserIconOverlay">
            <Image Type="Middle">icon_chat</Image>
        </Images>
    </Component>
    
    
    
    <!--
    //////////////////////////////////////////////
    // Buttons
    //////////////////////////////////////////////
    -->
    <Component Name="XIGHelpButtonBar" Class="Tile" MinHeight="84" MaxHeight="84" Stretch="ToContent" Events="Transparent">
        <Images State="Normal">
            <Image Type="TopLeft">button_bar_left_large</Image>
            <Image Type="Top">button_bar_middle_large</Image>
            <Image Type="TopRight">button_bar_right_large</Image>
        </Images>
    </Component>
</Components>
